# Generated by Django 4.2.5 on 2023-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
